# Generated by Django 3.2.20 on 2023-08-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slub',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
